version: "3"
services:
  node:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=menusaz
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
